# Site settings
author: Arnold Bwaila
title: Arnold Bwaila Ruby Portfolio
header-img: img/home-bg.png
email: arnold.bwaila@gmail.com
copyright_name: Arnold Bwaila
description: > # this means to ignore newlines until "baseurl:"
  Ruby Progress Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dlonra22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
